title: QuocBuu
lang: en-US
description: Embedded Software Engineer — Portfolio
author: Quoc Buu

edit: false

copyright:
  revision: false

addons:
  - github

theme: null

sass:
  style: compressed

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
  - ci.sh
  - CODE_OF_CONDUCT.md
  - LICENSE
  - jekyll-rtd-theme.gemspec
  - test/
  - test-long/
  - docs/
